apiVersion: v1
kind: PersistentVolume
metadata:
  name: url-shortener-pv
  namespace: url-shortener
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/url-shortener
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: url-shortener-pvc
  namespace: url-shortener
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi