apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-app
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-app
  template:
    metadata:
      labels:
        app: url-shortener-app
    spec:
      containers:
        - name: url-shortener-app
          image: ahmedanas04/url-shortener:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: BASE_URL
              value: "http://localhost:9000"
          volumeMounts:
            - name: data-storage
              mountPath: /app/data
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: url-shortener-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: url-shortener
spec:
  type: NodePort
  selector:
    app: url-shortener-app
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090