apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: url-shortener
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'url-shortener'
        metrics_path: /metrics
        static_configs:
          - targets: ['url-shortener-service:9000']