{
 "title": "URL Shortener Service Dashboard",
 "tags": [
  "prometheus",
  "url-shortener",
  "observability"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total URLs Shortened (Stat)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total URLs Shortened",
     "type": "stat",
     "description": "A single big number showing total count of URLs ever shortened.",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "url_shortened_total{instance=\"app:9000\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "95th Percentile Latency  ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "95th Percentile Latency by Endpoint",
     "type": "timeseries",
     "description": "Track near-worst-case performance — how slow requests are for users.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le, endpoint))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Creation Rate | Redirect Rate | 404 Rate  ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "404 Error Rate (per second)",
     "type": "timeseries",
     "description": "Detect broken links or invalid requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      { "expr": "rate(lookup_failed_total[5m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Redirect Rate (per Second)",
     "type": "timeseries",
     "description": "Shows how often users are being redirected",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(redirect_success_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "URL Creation Rate (per second)",
     "type": "timeseries",
     "description": "Shows how frequently new short URLs are created.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "rate(url_shortened_total[5m])", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}